extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings

#plugins:
#  - import

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

env:
  node: true

rules:
  no-console: 0
  
